### ISSUE TITLE
If project created with Studio and there is no create-db.sql scripts CLI should create them

### ISSUE THREAD

**Issue by jreznot** [cuba-platform/cuba-cli#108]
### Environment

- CLI version: 1.0.0

### Description of the bug or enhancement

- Minimal reproducible example

1. Create project with Studio
2. Try to create entity with CLI

- Expected behavior

CLI should create create-db.sql script

- Actual behavior

CLI prints:
```
Unable to find create script
```

**Comment by jreznot** [comment]
Reopened.

Please note that db directory most likely is not created too:
```
java.nio.file.NoSuchFileException: /home/artamonov/projects/crazy-monkey/modules/core/db/init/hsql/10.create-db.sql
        at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
        at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:215)
        at java.base/java.nio.file.Files.newByteChannel(Files.java:369)
        at java.base/java.nio.file.Files.createFile(Files.java:640)
        at com.haulmont.cuba.cli/com.haulmont.cuba.cli.cubaplugin.entity.CreateEntityCommand.createSqlScripts(CreateEntityCommand.kt:148)
        at com.haulmont.cuba.cli/com.haulmont.cuba.cli.cubaplugin.entity.CreateEntityCommand.generate(CreateEntityCommand.kt:127)
        at com.haulmont.cuba.cli/com.haulmont.cuba.cli.commands.GeneratorCommand.run(GeneratorCommand.kt:75)
        at com.haulmont.cuba.cli/com.haulmont.cuba.cli.commands.AbstractCommand.execute(AbstractCommand.kt:34)
        at com.haulmont.cuba.cli/com.haulmont.cuba.cli.ShellCli.evalCommand(ShellCli.kt:116)
        at com.haulmont.cuba.cli/com.haulmont.cuba.cli.ShellCli.run(ShellCli.kt:108)
        at com.haulmont.cuba.cli/com.haulmont.cuba.cli.EntryPointKt.main(EntryPoint.kt:112)
```
