### ISSUE TITLE
The "idea" command execution fails when CLI ran from IDEA

### ISSUE THREAD

**Issue by myatlevEvg** [cuba-platform/cuba-cli#175]
1) Run CLI in IDEA
2) Execute "idea" command

AR: Exception occurs

```
* What went wrong:
> Unable to connect to the IDE. Check if the IDE is running and CUBA Plugin is installed.

com.haulmont.cuba.cli.commands.CommandExecutionException: Unable to connect to the IDE. Check if the IDE is running and CUBA Plugin is installed.
        at com.haulmont.cuba.cli/com.haulmont.cuba.cli.commands.AbstractCommand.fail(AbstractCommand.kt:87)
        at com.haulmont.cuba.cli/com.haulmont.cuba.cli.commands.AbstractCommand.fail$default(AbstractCommand.kt:86)
        at com.haulmont.cuba.cli/com.haulmont.cuba.cli.cubaplugin.idea.IdeaOpenCommand.run(IdeaOpenCommand.kt:50)
        at com.haulmont.cuba.cli/com.haulmont.cuba.cli.commands.AbstractCommand.execute(AbstractCommand.kt:49)
        at com.haulmont.cuba.cli/com.haulmont.cuba.cli.ShellCli.evalCommand(ShellCli.kt:135)
        at com.haulmont.cuba.cli/com.haulmont.cuba.cli.ShellCli.run(ShellCli.kt:118)
        at com.haulmont.cuba.cli/com.haulmont.cuba.cli.EntryPointKt.main(EntryPoint.kt:113)

```

**Comment by alexander-shustanov** [comment]
Fixed integration port. Added message about enabling option `Old studio integration support`
